sudo: false
language: bash
os:
  - linux
before_install:
  - cp config.cfg.example config.cfg
install:
  - shellcheck --version
  - go get -u mvdan.cc/sh/cmd/shfmt
script:
  - shellcheck $TRAVIS_BUILD_DIR/gitbackup.sh
  - shfmt -i 2 -d -p -ci $TRAVIS_BUILD_DIR/gitbackup.sh
